apiVersion: v1
kind: ReplicationController
metadata:
  name: testing
spec:
  replicas: 5
  selector:
    app: frontend
  template:
    metadata:
      name: rc-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:stable 
