apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testing
spec:
  replicas: 5
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      name: replica-pod
      labels:
        app: production
    spec:
      containers:
      - name: replica-container
        image: nginx
